name: Build
on: push

jobs:
  fmt_clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Lint (rustfmt)
        run: cargo fmt -- --check
      - name: Lint (clippy)
        run: cargo clippy --all-targets --all-features -- -D warnings
      
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - arm-unknown-linux-musleabihf
          - armv7-unknown-linux-musleabihf
          - aarch64-unknown-linux-musl
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          target: ${{ matrix.target }}
      - name: Install set-cargo-version
        run: cargo install set-cargo-version
      - name: Change frontend version to commit hash
        working-directory: frontend
        run: npm version $(git describe --tags) --allow-same-version
      - name: Change backend version to commit hash
        run: set-cargo-version Cargo.toml $(git describe --tags | cut -c 2-)
      - name: Run build script
        run: cargo check --target ${{ matrix.target }} --release
      - name: Build DietPi-Dashboard
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=${{ matrix.target }}
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: dietpi-dashboard-x86_64
          path: target/${{ matrix.target }}/release/dietpi-dashboard
      - name: Build DietPi-Dashboard (backend only)
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=${{ matrix.target }} --no-default-features
      - name: Upload binary (backend only)
        uses: actions/upload-artifact@v2
        with:
          name: dietpi-dashboard-x86_64
          path: target/${{ matrix.target }}/release/dietpi-dashboard