name: Build
on: push

jobs:
  build:
    if: "!startsWith(github.event.head_commit.message, 'docs') && !startsWith(github.event.head_commit.message, 'style')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Lint (rustfmt)
        working-directory: src/backend
        run: cargo fmt -- --check
      - name: Install other Rust targets
        run: |
          rustup target add aarch64-unknown-linux-musl
      - name: Restore Rust cache
        uses: Swatinem/rust-cache@v1
        with:
          working-directory: src/backend
      - name: Lint (clippy)
        working-directory: src/backend
        run: |
          mkdir dist
          cargo clippy --all-targets --all-features -- -D warnings
      - name: Install Rust dependencies
        run: cargo install cross set-cargo-version
      - name: Install Yarn Dependencies
        working-directory: src/frontend
        run: yarn install
      - name: Change frontend version to commit hash
        working-directory: src/frontend
        run: npm version $(git describe --tags) --allow-same-version
      - name: Change backend version to commit hash
        run: set-cargo-version src/backend/Cargo.toml $(git describe --tags | cut -c 2-)
      - name: Build frontend
        working-directory: src/frontend
        run: yarn build
      - name: Compress frontend files
        run: make compress
      - name: Build armv6l
        working-directory: src/backend
        run: cross build --release --target arm-unknown-linux-musleabihf --features compression
      - name: Build aarch64
        working-directory: src/backend
        run: cross build --release --target aarch64-unknown-linux-musl --features compression
      - uses: actions/upload-artifact@v2
        with:
          name: dietpi-dashboard-aarch64
          path: src/backend/target/aarch64-unknown-linux-musl/release/dietpi-dashboard
